- .github/workflows/VerifyAction.yml
- src/test/java/com/neopragma/cobolcheck/ConfigIT.java
- src/test/java/com/neopragma/cobolcheck/PathHelperTest.java
The following changes are a suggestion on how to automate pull requests, and thus minimizing management time, and approval time for pull requests.
A GitHub Action has been set up to run tests and approval tests when pushing a branch. Note; currently any pushed branch will start this Action. Tests will run on Ubuntu 18.04, Windows Server 2019 and macOS 10.15, all on both JDK 8 and 11.
Some tests have been corrected, in order for all tests to succeed on all above mentioned platforms and Java versions.
> Step towards automation

- src/main/cobol/MOCKTEST.CBL
- src/main/java/com/neopragma/cobolcheck/features/interpreter/CobolReader.java
- src/main/java/com/neopragma/cobolcheck/features/interpreter/Interpreter.java
- src/main/java/com/neopragma/cobolcheck/features/interpreter/InterpreterController.java
- src/main/java/com/neopragma/cobolcheck/features/testSuiteParser/Mock.java
- src/main/java/com/neopragma/cobolcheck/features/testSuiteParser/MockGenerator.java
- src/main/java/com/neopragma/cobolcheck/features/testSuiteParser/MockRepository.java
- src/main/java/com/neopragma/cobolcheck/features/testSuiteParser/TestSuiteParser.java
- src/main/java/com/neopragma/cobolcheck/features/testSuiteParser/TestSuiteParserController.java
- src/main/java/com/neopragma/cobolcheck/features/testSuiteParser/VerifyMockCount.java
- src/main/java/com/neopragma/cobolcheck/features/writer/CobolWriter.java
- src/main/java/com/neopragma/cobolcheck/features/writer/WriterController.java
- src/main/java/com/neopragma/cobolcheck/services/Constants.java
- src/main/java/com/neopragma/cobolcheck/workers/Generator.java
- src/main/resources/com/neopragma/cobolcheck/copybooks/CCHECKPD.CPY
- src/main/resources/com/neopragma/cobolcheck/messages/messages.properties
- src/test/cobol/MOCKTEST/MockTest
- src/test/java/com/neopragma/cobolcheck/ConfigIT.java
- src/test/java/com/neopragma/cobolcheck/InterpreterControllerTest.java
- src/test/java/com/neopragma/cobolcheck/InterpreterTest.java
- src/test/java/com/neopragma/cobolcheck/MockIT.java
- src/test/java/com/neopragma/cobolcheck/MockingTest.java
- src/test/java/com/neopragma/cobolcheck/PathHelperTest.java
- src/test/java/com/neopragma/cobolcheck/TestSuiteParserParsingTest.java
- src/test/java/com/neopragma/cobolcheck/writerTest.java
- When a mocked `SECTION `or `PARAGRAPH `ends, an "`END-EVALUATE`" line needs to be inserted. Before it could not handle periods on the same line as some other code, as the "`END-EVALUATE`"-line would be inserted before this. It also did not account for the `EXIT`-token. This is now fixed.
- Mocks and verify statements are now strongly typed - meaning cobol-check wil throw an error or log a warning if the wrong type is referenced in a mock or a verify.
- Logs a warning when a mock does not reference a component from the source code
- Fixed mock values being carried on to non-meaningful lines.
- Added mock integration tests.
- Uncommented tests regarding `Interpreter.getBeginningArea.`
- Writer can now handle continuation lines, when the string is started with an apostrophe: ' (tests has …
> Bug fixes and structural changes regarding mocks

- CC##99.CBL
- approval-test-expected.txt
- src/main/cobol/MOCKTEST.CBL
- src/main/java/com/neopragma/cobolcheck/features/testSuiteParser/BeforeAfterRepo.java
- src/main/java/com/neopragma/cobolcheck/features/testSuiteParser/CobolGenerator.java
- src/main/java/com/neopragma/cobolcheck/features/testSuiteParser/EvaluationGenerator.java
- src/main/java/com/neopragma/cobolcheck/features/testSuiteParser/KeywordExtractor.java
- src/main/java/com/neopragma/cobolcheck/features/testSuiteParser/Keywords.java
- src/main/java/com/neopragma/cobolcheck/features/testSuiteParser/MockGenerator.java
- src/main/java/com/neopragma/cobolcheck/features/testSuiteParser/TestSuiteParser.java
- src/main/java/com/neopragma/cobolcheck/features/testSuiteParser/TestSuiteParserController.java
- src/main/java/com/neopragma/cobolcheck/services/Config.java
- src/main/java/com/neopragma/cobolcheck/services/Constants.java
- src/test/cobol/MOCKTEST/BeforeAfterTest
- src/test/java/com/neopragma/cobolcheck/MockIT.java
- src/test/java/com/neopragma/cobolcheck/MockingTest.java
- src/test/java/com/neopragma/cobolcheck/TestSuiteParserCodeInsertionTest.java
- src/test/java/com/neopragma/cobolcheck/TestSuiteParserParsingTest.java
- testResults.txt
- Implemented Before and After each
- Streamlined cobol code generation in regard to paragraphs, comment blocks and evaluations
- Added tests for Before/After
- Small fixes and refactoring
> Before after each

- .github/workflows/DeployExtension.yml
- vs code extension/CHANGELOG.md
- vs code extension/README.md
- vs code extension/client/package.json
- vs code extension/client/src/test/helper.ts
- vs code extension/package.json
- vs code extension/server/package.json
Added github action for deploying vs code extension
> Deploy extension

- src/main/java/org/openmainframeproject/cobolcheck/features/testSuiteParser/Keywords.java
- src/main/java/org/openmainframeproject/cobolcheck/features/testSuiteParser/TestSuiteParser.java
- src/test/java/org/openmainframeproject/cobolcheck/KeywordsTest.java
- src/test/java/org/openmainframeproject/cobolcheck/TestSuiteParserParsingTest.java
Fixed advanced COBOL-statements not being properly generated from cut-file
> Bug fixes2

- src/main/java/org/openmainframeproject/cobolcheck/Main.java
- src/main/java/org/openmainframeproject/cobolcheck/features/Status/StatusController.java
- Fixed bug where Cobol Check would not terminate after showing --version or --help
- Added back return code for halt, that was removed by mistake
> Fixed help and version functions

- vs code extension/client/src/Helpers/PathHelper.ts
- vs code extension/client/src/services/CobolCheckOutputParser.ts
Signed-off-by: David Kaan <davidkaan@gmail.com>
> Fixed warning overwriting compile error

- build.gradle
- cobolcheck
- cobolcheck.cmd
- src/main/java/org/openmainframeproject/cobolcheck/features/Status/Emitter.java
- src/main/java/org/openmainframeproject/cobolcheck/services/Version.java
- src/test/java/org/openmainframeproject/cobolcheck/VersionTest.java
> Deploy automation

- src/main/cobol/MOCKTEST.CBL
- src/main/java/org/openmainframeproject/cobolcheck/services/cobolLogic/Interpreter.java
Added support for comments starting with '/' in  source file (still needs further implementation for UT and too long lines in Writer)
> Fixed comments with '/'

- CHANGELOG.md
- vs code extension/CHANGELOG.md
Signed-off-by: dakaa16 <davidkaan@gmail.com>
> Updated changelogs with new dates

- vs code extension/CHANGELOG.md
- vs code extension/client/src/extension.ts
- vs code extension/package.json
Signed-off-by: dakaa16 <davidkaan@gmail.com>
> Fixed wrong jar version

- CHANGELOG.md
- README.md
- build.gradle
- src/main/cobol/NUMBERS.CBL
- src/main/java/org/openmainframeproject/cobolcheck/features/interpreter/InterpreterController.java
- src/main/java/org/openmainframeproject/cobolcheck/features/testSuiteParser/KeywordExtractor.java
- src/main/java/org/openmainframeproject/cobolcheck/features/testSuiteParser/TestSuiteParser.java
- src/main/java/org/openmainframeproject/cobolcheck/services/Constants.java
- src/main/java/org/openmainframeproject/cobolcheck/services/cobolLogic/DataType.java
- src/main/java/org/openmainframeproject/cobolcheck/services/cobolLogic/Interpreter.java
- src/main/java/org/openmainframeproject/cobolcheck/services/cobolLogic/NumericFields.java
- src/test/cobol/NUMBERS/SymbolicRelationsTest.cut
- src/test/java/org/openmainframeproject/cobolcheck/InterpreterControllerTest.java
Signed-off-by: WildtBrian <brw@bankdata.dk>
> version 0.2.7 - bugfixes

- README.md
fix: #110 
Removed the "build status" and "quality gate statues" from readme as asked by @Rune-Christensen!
> Remove "build status" & "quality gate status"

- scripts/windows_gnucobol_run_tests.cmd
> Fixed cobolcheck cannot handle spaces in path

- src/main/java/org/openmainframeproject/cobolcheck/exceptions/TestCaseAlreadyExistsException.java
- src/main/java/org/openmainframeproject/cobolcheck/exceptions/TestSuiteAlreadyExistsException.java
- src/main/java/org/openmainframeproject/cobolcheck/features/testSuiteParser/TestSuiteParser.java
- src/main/resources/org/openmainframeproject/cobolcheck/messages/messages.properties
- src/test/java/org/openmainframeproject/cobolcheck/TestSuiteParserParsingTest.java
> 217 add duplication check for test suites and test cases

- src/main/cobol/MOCKTEST.CBL
- src/main/java/org/openmainframeproject/cobolcheck/features/interpreter/CobolReader.java
- src/main/java/org/openmainframeproject/cobolcheck/features/interpreter/InterpreterController.java
- src/main/java/org/openmainframeproject/cobolcheck/features/writer/CobolWriter.java
- src/main/java/org/openmainframeproject/cobolcheck/services/cobolLogic/Interpreter.java
- src/test/cobol/MOCKTEST/MockCallTest.cut
- src/test/java/org/openmainframeproject/cobolcheck/ExpanderTest.java
- src/test/java/org/openmainframeproject/cobolcheck/MockIT.java
- src/test/java/org/openmainframeproject/cobolcheck/writerTest.java
> 276 Support on Exception in CALLs

- config.properties
- src/main/java/org/openmainframeproject/cobolcheck/features/testSuiteParser/MockGenerator.java
- src/main/java/org/openmainframeproject/cobolcheck/features/testSuiteParser/TestSuiteParserController.java
- src/main/java/org/openmainframeproject/cobolcheck/services/Config.java
- src/main/java/org/openmainframeproject/cobolcheck/workers/Generator.java
- src/main/resources/org/openmainframeproject/cobolcheck/copybooks/CCHECKRESULTPD.CPY
- src/main/resources/org/openmainframeproject/cobolcheck/copybooks/CCHECKWS.CPY
- src/test/java/org/openmainframeproject/cobolcheck/ExpanderTest.java
- src/test/java/org/openmainframeproject/cobolcheck/MockIT.java
- src/test/java/org/openmainframeproject/cobolcheck/MockingTest.java
- testconfig.properties
> feature 288 alert when call statement is not mocked

- vs code extension/package.json
* license per distributed file
* repo URL and issue-tracker
> vscode extension: update metadata

- README.md
> Fix: update links

- CHANGELOG.md
- README.md
- build.gradle
- src/main/java/org/openmainframeproject/cobolcheck/Main.java
- src/main/java/org/openmainframeproject/cobolcheck/workers/Initializer.java
- vs-code-extension/CHANGELOG.md
- vs-code-extension/client/src/extension.ts
- vs-code-extension/client/src/services/TestTree.ts
- vs-code-extension/package.json
* Removed exit code check to be anything ABOVE 4.
> Fixed - A bug where error code of 4 was not allowed so failing tests would not be shown properly
